server:
  port: ${PORT:8082}

spring:
  application:
    name: package-service-api

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12qwaszx


  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  cloud:
    stream:
      kafka:
        streams:
          binder:
            applicationId: ${spring.application.name}
        binder:
          brokers: localhost:9092
      function:
        definition: cardTopic;

      bindings:
        card-topic-out-0:
          destination: card-topic

        cardTopic-in-0:
          destination: card-topic
          group: ${spring.application.name}