spring:
  data:
    mongodb:
      uri: mongodb+srv://adminMongo:1234qwer@contactkeeper.ixcdp.mongodb.net/transaction?retryWrites=true&w=majority

feign:
  hystrix:
    enabled: true

client:
  card-api:
    value: cards
    url: http://localhost:8081/cards